// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20201026180218_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<string>("Review");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = -1,
                            Date = new DateTime(2020, 10, 26, 11, 2, 18, 159, DateTimeKind.Local).AddTicks(8530),
                            Name = "Las Vegas",
                            Rating = 7,
                            Review = "Hot"
                        },
                        new
                        {
                            PlaceId = -2,
                            Date = new DateTime(2020, 10, 26, 11, 2, 18, 172, DateTimeKind.Local).AddTicks(2580),
                            Name = "NYC",
                            Rating = 10,
                            Review = "Crowded"
                        },
                        new
                        {
                            PlaceId = -3,
                            Date = new DateTime(2020, 10, 26, 11, 2, 18, 172, DateTimeKind.Local).AddTicks(2600),
                            Name = "Portland",
                            Rating = 2,
                            Review = "Bridges"
                        },
                        new
                        {
                            PlaceId = -4,
                            Date = new DateTime(2020, 10, 26, 11, 2, 18, 172, DateTimeKind.Local).AddTicks(2600),
                            Name = "Seattle",
                            Rating = 4,
                            Review = "Hills"
                        },
                        new
                        {
                            PlaceId = -5,
                            Date = new DateTime(2020, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Miami",
                            Rating = 22,
                            Review = "Beaches"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
